image: node:latest

stages:
  - install
  - build
  - test

Build:
  stage: build
  tags:
    - node
  before_script:
    - npm install
  script:
    - npm run build

Test:
  stage: test
  tags:
    - node
  script:
    - npm run test
